---
- name: Install engineering tools
  pacman:
    name:
      - kicad
      - ros-melodic-desktop-full  # Example ROS package
      - android-studio
      - arduino
      - gnuradio
    state: present

