---
- name: Set up Homebrew
  hosts: localhost
  become: yes
  vars:
    homebrew_prefix: "/home/linuxbrew/.linuxbrew"
    brew_packages:
      - httpie
      - eza

  tasks:
    - name: Ensure build dependencies are installed
      apt:
        name:
          - build-essential
          - curl
          - file
          - git
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure homebrew directory exists
      file:
        path: "{{ homebrew_prefix }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: '0755'

    - name: Install Homebrew
      become: false
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: "{{ homebrew_prefix }}/bin/brew"

    - name: Ensure Homebrew is in the path
      shell: |
        echo 'eval "$({{ homebrew_prefix }}/bin/brew shellenv)"' >> ~/.profile
        eval "$({{ homebrew_prefix }}/bin/brew shellenv)"
      become: false

    - name: Verify Homebrew installation
      command: "{{ homebrew_prefix }}/bin/brew --version"
      register: brew_version
      ignore_errors: yes

    - name: Debug Homebrew version
      debug:
        msg: "{{ brew_version.stdout }}"

    - name: Install Homebrew packages
      become: false
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_packages }}"
      when: brew_version is not failed

