---
- name: Install scientific computing tools
  pacman:
    name:
      - sagemath
      - octave
      - r
      - texlive-most
    state: present

- name: Install Miniconda
  shell: |
    curl -o ~/miniconda.sh -L https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    bash ~/miniconda.sh -b -p $HOME/miniconda
    rm ~/miniconda.sh
  args:
    creates: ~/miniconda

