# roles/asdf/tasks/main.yml
- name: Install ASDF
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: ~/.asdf
    version: v0.8.0

- name: Add ASDF to bashrc
  lineinfile:
    path: ~/.bashrc
    line: '. $HOME/.asdf/asdf.sh'

