# roles/common/tasks/main.yml
- name: Update and upgrade APT packages
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Update and upgrade Pacman packages
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_os_family == "Archlinux"

