---
# Ensure pipx is installed
- name: Ensure pipx is installed
  become: True
  community.general.pacman:
    name: python-pipx
    state: present

- name: Install pipx packages
  community.general.pipx:
        name: "{{ item }}"
        state: present
  loop: "{{ pipx_packages }}"
