---
- name: Setup Window Manager and Tools on Arch Linux
  hosts: all
  become: true

  vars:
    use_xmonad: true   # Set to true or false based on your preference
    use_qtile: true    # Set to true or false based on your preference
    use_gnome: false   # Set to true or false based on your preference
    use_kde: false     # Set to true or false based on your preference

  tasks:
    - name: Update package database
      pacman:
        update_cache: yes

    - name: Install XMonad and related tools
      when: use_xmonad
      pacman:
        name:
          - xmonad
          - xmonad-contrib
          - xmobar
          - xdotool
          - picom
          - feh
          - i3lock
          - rofi
          - eww
          - polybar
        state: present

    - name: Install Qtile and related tools
      when: use_qtile
      pacman:
        name:
          - qtile
          - xdotool
          - picom
          - feh
          - rofi
          - eww
          - polybar
        state: present

    - name: Install GNOME
      when: use_gnome
      pacman:
        name:
          - gnome
          - gnome-tweaks
          - gnome-shell-extensions
        state: present

    - name: Install KDE
      when: use_kde
      pacman:
        name:
          - plasma
          - kde-applications-meta
        state: present

    - name: Install common utilities
      pacman:
        name:
          - evince
          - thunar
          - dunst
          - nitrogen
        state: present

    - name: Install YubiKey support tools
      pacman:
        name:
          - yubikey-manager
          - yubico-piv-tool
          - yubikey-personalization
          - gnupg
          - ccid
        state: present

    - name: Configure YubiKey
      block:
        - name: Enable ccid service for YubiKey
          systemd:
            name: pcscd
            enabled: yes
            state: started

        - name: Set up GPG for YubiKey
          shell: |
            gpg --card-status

        - name: YubiKey Manager setup
          command: ykman info

