---
- name: Install GNS3 for network simulation
  pacman:
    name:
      - gns3-gui
      - gns3-server
    state: present

- name: Install additional network tools
  pacman:
    name:
      - wireshark-qt
      - tcpdump
      - nmap
      - openvpn
    state: present

- name: Install Wireshark CLI tools
  pacman:
    name:
      - wireshark-cli
    state: present

- name: Install network security tools
  pacman:
    name:
      - metasploit
      - ettercap-gtk
      - aircrack-ng
    state: present

